apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "api-coursetraker-cert"
  namespace: "staging"
spec:
  domain: "api.staging.coursetrakr.io"
  email: "tev.jeffrey@gmail.com"
  provider: "namecheap"
  secretName: api-staging-tls