apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-cert-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-cert-manager
rules:
  - apiGroups: [ "*" ]
    resources: [ "certificates", "ingresses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "*" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "create", "update", "delete" ]
  - apiGroups: [ "*" ]
    resources: [ "events" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-cert-manager-service-account
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: kube-cert-manager
roleRef:
  kind: ClusterRole
  name: kube-cert-manager
  apiGroup: rbac.authorization.k8s.io
