apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: edward-http
  labels:
    app: edward
spec:
  ports:
  - port: 2058
    protocol: "TCP"
    targetPort: 2058
    name: edward-port
  selector:
    app: edward