apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: production
  name: spike
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: spike
    spec:
      containers:
        - name: spike
          image: docker.io/tevjef/spike:production
          imagePullPolicy: "Always"
          ports:
          - containerPort: 13100
            name: pprof
          - containerPort: 13000
            name: metrics-port       
            protocol: TCP
          - containerPort: 9876
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /v2/universities
              port: 9876
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-cred
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-cred
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-cred
                  key: database-name
            - name: SPIKE_GCP_PROJECT
              value: universitycoursetracker
          resources:
            requests:
              cpu: "5m"
              memory: 50Mi
