apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  labels:
    app: cuny-bcc
  name: cuny-bcc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cuny-bcc
    spec:
      containers:
        - name: cuny-bcc
          image: docker.io/tevjef/cuny:staging
          ports:
          - containerPort: 13100
            name: pprof
          - containerPort: 13000
            name: uct-metrics
            protocol: TCP
          imagePullPolicy: Always
          env:
          - name: CUNY_UNIVERSITY
            value: BCC
          - name: JET_DAEMON
            value: 10m
          - name: JET_DAEMON_JITTER
            value: "50"
          - name: JET_SCRAPER_NAME
            value: cuny-bcc