apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  labels:
    app: cuny-bar
  name: cuny-bar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cuny-bar
    spec:
      containers:
        - name: cuny-bar
          image: docker.io/tevjef/cuny:staging
          ports:
            - containerPort: 13100
              name: pprof
            - containerPort: 13000
              name: metrics-port
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: CUNY_UNIVERSITY
              value: BAR
            - name: JET_DAEMON
              value: 15m
            - name: JET_DAEMON_JITTER
              value: "50"
            - name: JET_SCRAPER_NAME
              value: cuny-bar
          resources:
            requests:
              memory: 50Mi