apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: njit
  labels:
    app: njit
spec:
  selector:
    app: njit
  ports:
  - name: uct-metrics
    port: 13000
    protocol: TCP
    targetPort: uct-metrics
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  labels:
    app: njit
  name: njit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: njit
    spec:
      containers:
        - name: njit
          image: docker.io/tevjef/uct-core:njit-staging
          ports:
          - containerPort: 13100
            name: pprof
          - containerPort: 13000
            name: uct-metrics
            protocol: TCP
          imagePullPolicy: Always
          env:
          - name: JET_DAEMON
            value: 10m
          - name: JET_SCRAPER_NAME
            value: njit
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: njit
  labels:
    metrics: njit
spec:
  jobLabel: njit
  selector:
    matchLabels:
      app: njit
  namespaceSelector:
    matchNames:
    - staging
  endpoints:
  - port: uct-metrics
    interval: 15s
    honorLabels: true
