apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  labels:
    app: njit
  name: njit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: njit
    spec:
      containers:
        - name: njit
          image: docker.io/tevjef/uct-core:njit-staging
          ports:
          - containerPort: 13100
            name: pprof
          - containerPort: 13000
            name: uct-metrics
            protocol: TCP
          imagePullPolicy: Always
          env:
          - name: JET_DAEMON
            value: 10m
          - name: JET_SCRAPER_NAME
            value: njit