apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: rutgers-cm
  labels:
    metrics: rutgers-cm
spec:
  jobLabel: rutgers-cm
  selector:
    matchLabels:
      app: rutgers-cm
  namespaceSelector:
    matchNames:
    - staging
  endpoints:
  - port: uct-metrics
    interval: 15s
    honorLabels: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: rutgers-cm
  labels:
    app: rutgers-cm
spec:
  selector:
    app: rutgers-cm
  ports:
  - name: uct-metrics
    port: 13000
    protocol: TCP
    targetPort: uct-metrics