apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: julia
  name: julia
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: julia
    spec:
      containers:
      - image: docker.io/tevjef/julia:production
        name: julia
        imagePullPolicy: Always
        ports:
        - containerPort: 13100
          name: pprof
        - containerPort: 13000
          name: metrics-port
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: database-name
        resources:
          requests:
            memory: 50Mi
