apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: production
  labels:
    app: njit
  name: njit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: njit
    spec:
      containers:
        - name: njit
          image: docker.io/tevjef/njit:production
          ports:
            - containerPort: 13100
              name: pprof
            - containerPort: 13000
              name: metrics-port
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: JET_DAEMON
              value: 15m
            - name: JET_SCRAPER_NAME
              value: njit
          resources:
            requests:
              memory: 50Mi
