apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: njit
  labels:
    metrics: njit
spec:
  jobLabel: njit
  selector:
    matchLabels:
      app: njit
  namespaceSelector:
    matchNames:
      - staging
      - production
  endpoints:
    - port: metrics-port
      interval: 15s
      honorLabels: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: njit
  labels:
    app: njit
    metrics: "true"
spec:
  selector:
    app: njit
  ports:
    - name: metrics-port
      port: 13000
      protocol: TCP
      targetPort: metrics-port
