apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: rutgers-cm
  labels:
    metrics: rutgers-cm
spec:
  jobLabel: rutgers-cm
  selector:
    matchLabels:
      app: rutgers-cm
  namespaceSelector:
    matchNames:
    - staging
    - production
  endpoints:
  - port: metrics-port
    interval: 15s
    honorLabels: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: rutgers-cm
  labels:
    app: rutgers-cm
    metrics: "true"
spec:
  selector:
    app: rutgers-cm
  ports:
  - name: metrics-port
    port: 13000
    protocol: TCP
    targetPort: metrics-port
