apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubernetes-cockpit
  name: kubernetes-cockpit
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-cockpit
    spec:
      serviceAccountName: dashboard
      containers:
      - env:
        - name: KUBE_INSECURE
          value: "false"
        image: cockpit/kubernetes:latest
        imagePullPolicy: Always
        name: kubernetes-cockpit
        ports:
        - containerPort: 9090
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-cockpit
  name: kubernetes-cockpit
  namespace: kube-system
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: kubernetes-cockpit
  type: ClusterIP
