kind: Service
metadata:
  namespace: staging
  name: julia
  labels:
    app: julia
    metrics: "true"
spec:
  selector:
    app: julia
  ports:
  - name: metrics-port
    port: 13000
    protocol: TCP
    targetPort: metrics-port
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: julia
  labels:
    metrics: julia
spec:
  jobLabel: julia
  selector:
    matchLabels:
      app: julia
  namespaceSelector:
    matchNames:
    - staging
  endpoints:
  - port: metrics-port
    interval: 15s
    honorLabels: true