apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone
  namespace: staging
rules:
- apiGroups: ["*"]
  resources:
  - deployments
  - servicemonitors
  - cronjobs
  - configmaps
  - services
  verbs: ["get","patch","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone
subjects:
- kind: ServiceAccount
  name: drone-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone
  namespace: monitoring
rules:
- apiGroups: ["*"]
  resources:
  - servicemonitors
  verbs: ["get","patch","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone
subjects:
- kind: ServiceAccount
  name: drone-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone
  namespace: production
rules:
- apiGroups: ["*"]
  resources:
  - deployments
  - servicemonitors
  - services
  verbs: ["get","patch","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone
subjects:
- kind: ServiceAccount
  name: drone-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: drone-sa
