apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  name: vt
spec:
  template:
    metadata:
      labels:
        app: vt
    spec:
      containers:
        - name: vt
          image: docker.io/tevjef/vt:develop
          imagePullPolicy: "Always"
          ports:
          - name: vt-grpc
            containerPort: 9875
            protocol: TCP
          env:
          - name: CREDENTIALS_LOCATION
            value: /etc/vt/sa.json
          - name: VT_PORT
            value: "9875"
          volumeMounts:
          - name: vt-secret
            mountPath: /etc/vt
            readOnly: true
      volumes:
      - name: vt-secret
        secret:
          secretName: vt-secret
          items:
          - key: sa.json
            path: sa.json