apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: production
  name: postgresql-backup
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql-backup
    spec:
      containers:
      - name: postgres-backup
        image: tevjef/postgres-backup
        imagePullPolicy: Always
        env:
          - name: SLEEP_SECONDS
            value: "86400"
          - name: PGHOST
            value: postgresql
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: pg-cred
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-cred
                key: password
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: pg-cred
                key: database-name
          - name: GCS_BUCKET
            valueFrom:
              secretKeyRef:
                name: gcs-cred
                key: gcs-bucket
          - name: GCS_PROJECT
            valueFrom:
              secretKeyRef:
                name: gcs-cred
                key: gcs-project
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/run/gcs/sa.json
        volumeMounts:
          - name: gcs-service-account
            mountPath: /var/run/gcs
      volumes:
        - name: gcs-service-account
          secret:
            secretName: gcs-cred
