apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hermes
  name: hermes
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
      - image: docker.io/tevjef/hermes:production
        name: hermes
        imagePullPolicy: Always
        ports:
        - containerPort: 13100
          name: pprof
        - containerPort: 13000
          name: metrics-port
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: database-name
        - name: HERMES_DRY_RUN
          valueFrom:
            secretKeyRef:
              name: hermes-cred
              key: dry-run
        - name: CREDENTIALS_LOCATION
          value: /etc/hermes/sa.json
        volumeMounts:
        - name: google-sa
          mountPath: /etc/hermes
          readOnly: true
        resources:
          requests:
            memory: 50Mi
      volumes:
      - name: google-sa
        secret:
          secretName: hermes-cred
          items:
          - key: sa.json
            path: sa.json
