apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:3
        name: redis
        ports: 
        - containerPort: 6379