apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hermes
  name: hermes
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
      - image: tevjef/uct-core:hermes-staging
        name: hermes
        imagePullPolicy: Always
        ports:
        - containerPort: 13000
          name: uct-metrics
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-cred
              key: database-name