kind: Service
metadata:
  namespace: staging
  name: hermes
  labels:
    app: hermes
spec:
  selector:
    app: hermes
  ports:
  - name: uct-metrics
    port: 13000
    protocol: TCP
    targetPort: uct-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: hermes
  labels:
    metrics: hermes
spec:
  jobLabel: hermes
  selector:
    matchLabels:
      app: hermes
  namespaceSelector:
    matchNames:
    - staging
  endpoints:
  - port: uct-metrics
    interval: 15s
    honorLabels: true